FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc g++ libffi-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir angr==9.2.119

WORKDIR /mnt/staging
CMD ["/bin/sh"]
